// <auto-generated />
#pragma warning disable 414
namespace WordLatexAddin
{
    [Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(0)]
    [global::System.Security.Permissions.PermissionSetAttribute(global::System.Security.Permissions.SecurityAction.Demand, Name = "FullTrust")]
    public sealed partial class ThisAddIn : Microsoft.Office.Tools.AddInBase
    {
        internal Microsoft.Office.Interop.Word.Application Application;

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public ThisAddIn(global::Microsoft.Office.Tools.Word.ApplicationFactory factory, global::System.IServiceProvider serviceProvider)
            : base(factory, serviceProvider, "AddIn", "ThisAddIn")
        {
            Globals.Factory = factory;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void Initialize()
        {
            base.Initialize();
            Application = GetHostItem<Microsoft.Office.Interop.Word.Application>(typeof(Microsoft.Office.Interop.Word.Application), "Application");
            Globals.ThisAddIn = this;
            global::System.Windows.Forms.Application.EnableVisualStyles();
            InitializeCachedData();
            InitializeData();
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FinishInitialization()
        {
            InternalStartup();
            OnStartup();
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDataBindings()
        {
            BeginInit();
            BindToData();
            EndInit();
        }

        private void InitializeCachedData()
        {
            if (DataHost != null && DataHost.IsCacheInitialized) DataHost.FillCachedData(this);
        }

        private void InitializeData() { }
        private void BindToData() { }
    }

    internal sealed partial class Globals
    {
        private static ThisAddIn _thisAddIn;
        private static global::Microsoft.Office.Tools.Word.ApplicationFactory _factory;

        private Globals() { }

        internal static ThisAddIn ThisAddIn
        {
            get { return _thisAddIn; }
            set
            {
                if (_thisAddIn != null) throw new global::System.NotSupportedException();
                _thisAddIn = value;
            }
        }

        internal static global::Microsoft.Office.Tools.Word.ApplicationFactory Factory
        {
            get { return _factory; }
            set
            {
                if (_factory != null) throw new global::System.NotSupportedException();
                _factory = value;
            }
        }
    }
}
